#!/usr/bin/env python

import sys
import copy
import submit_api


# hsub: Submission script for the Herd Volunteer Computing Project
# lwilson - TACC
# Usage: hsub <launcher_job_file>

if len(sys.argv) <= 1:
  print "Too few args!"
  print "Usage: hsub <launcher_job_file>"
  exit()


job_file=open(sys.argv[1], "r")

for wu in job_file:
  print wu

f = submit_api.FILE_DESC()
f.mode = 'remote'
f.url = 'http://isaac.ssl.berkeley.edu/validate_logic.txt'
f.md5 = "eec5a142cea5202c9ab2e4575a8aaaa7"
f.nbytes = 4250

job = submit_api.JOB_DESC()
job.files = [f]

batch = submit_api.BATCH_DESC()
batch.project = 'http://129.114.6.131/tacctest/'
batch.authenticator = '1f289518a167969cc67523ba7d5ced8a'
batch.app_name = "example_app"
batch.batch_name = "blah"
batch.jobs = []

for i in range(3):
    job.rsc_fpops_est = i*1e9
    job.command_line = '-i %s' %(i)
    batch.jobs.append(copy.copy(job))

r = submit_api.estimate_batch(batch)
if r.tag == 'error':
  print 'error: ', r.find('error_msg').text
  exit()
print 'estimated time: ', r.text, ' seconds'
